In [2]:
## To import numpy
import numpy as np

In [3]:
## Basics
a=np.array([1,2,3],dtype='int16') #1-D Array    we used (dtype='int16') bcz 1,2,3 are smaller value so to save size and fast processing we used int 16 else we used int64
print(a)
a.ndim

[1 2 3]


1

In [4]:
b=np.array([[1.0,5.0,7.0],[2.0,3.0,9.0]]) #2-D Array
print(b)
b.shape

[[1. 5. 7.]
 [2. 3. 9.]]


(2, 3)

In [5]:
c=np.array([[1,2,3],[4,5,6],[7,8,9]]) #2-D Array
print(c)
c.ndim

[[1 2 3]
 [4 5 6]
 [7 8 9]]


2

In [6]:
#Get Dimensions
a.ndim

1

In [7]:
# Get Shape
a.shape

(3,)

In [8]:
# Get Type
a.dtype

dtype('int16')

In [9]:
# Get Size
a.itemsize

2

In [10]:
# Get Total Size
a.nbytes

6

In [11]:
d=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(d)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [12]:
# lets say from above we want only one specific element lets say '13'
# [row,column]
d[1,5]

np.int64(13)

In [13]:
# You can also do like this 
d[1,-2]

np.int64(13)

In [14]:
# To get a specific row 
d[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [15]:
# To get a specif column
d[:,2]

array([ 3, 10])

In [16]:
# Getting little more fancey [start index: end index: stepsize]
d[0,1:6:2]

array([2, 4, 6])

In [17]:
# change an element in row
d[1,5]=20
print(d)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [18]:
# change elements in col
d[:,2]=[1,2]
print(d)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [19]:
# 3-d example
e=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(e)
e.shape

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


(2, 2, 2)

In [20]:
# get specific element from 3-d
e[0,1,1]

np.int64(4)

In [21]:
e[0,1,:]

array([3, 4])

In [22]:
e[:,1,:]

array([[3, 4],
       [7, 8]])

In [23]:
# To change something
e[:,1,:]=[[7,8],[3,4]]
print(e)

[[[1 2]
  [7 8]]

 [[5 6]
  [3 4]]]


In [24]:
#initialize differnet types of arrays
# ALL 0S Matrix
np.zeros(((2,3,3,2)))

#(2, 3, 3, 2)
 #↑  ↑  ↑  ↑
 #|  |  |  └─ columns
 #|  |  └──── rows
 #|  └─────── number of 3x2 matrices (each block has 3 matrices)
 #└────────── number of groups of those matrices (2 blocks)

 # basically its a 4-D matrix

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [27]:
# All 1s Matrix
np.ones((4,2,2),dtype='int16')
        #↑  ↑  ↑
 #.      |  |  └─ columns
 #.      |  └──── rows
 #       └─────── number of matricess

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int16)

In [34]:
# Any Other Number
np.full((2,2,2,2),99,dtype='float16')

array([[[[99., 99.],
         [99., 99.]],

        [[99., 99.],
         [99., 99.]]],


       [[[99., 99.],
         [99., 99.]],

        [[99., 99.],
         [99., 99.]]]], dtype=float16)

In [36]:
# Any Other NUmber (full-like method)
np.full_like(a,4)

array([4, 4, 4], dtype=int16)