In [2]:
## To import numpy
import numpy as np

In [3]:
## Basics
a=np.array([1,2,3],dtype='int16') #1-D Array    we used (dtype='int16') bcz 1,2,3 are smaller value so to save size and fast processing we used int 16 else we used int64
print(a)
a.ndim

[1 2 3]


1

In [4]:
b=np.array([[1.0,5.0,7.0],[2.0,3.0,9.0]]) #2-D Array
print(b)
b.shape

[[1. 5. 7.]
 [2. 3. 9.]]


(2, 3)

In [5]:
c=np.array([[1,2,3],[4,5,6],[7,8,9]]) #2-D Array
print(c)
c.ndim

[[1 2 3]
 [4 5 6]
 [7 8 9]]


2

In [6]:
#Get Dimensions
a.ndim

1

In [7]:
# Get Shape
a.shape

(3,)

In [8]:
# Get Type
a.dtype

dtype('int16')

In [9]:
# Get Size
a.itemsize

2

In [10]:
# Get Total Size
a.nbytes

6

In [11]:
d=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(d)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [12]:
# lets say from above we want only one specific element lets say '13'
# [row,column]
d[1,5]

np.int64(13)

In [13]:
# You can also do like this 
d[1,-2]

np.int64(13)

In [14]:
# To get a specific row 
d[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [15]:
# To get a specif column
d[:,2]

array([ 3, 10])

In [16]:
# Getting little more fancey [start index: end index: stepsize]
d[0,1:6:2]

array([2, 4, 6])

In [17]:
# change an element in row
d[1,5]=20
print(d)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [18]:
# change elements in col
d[:,2]=[1,2]
print(d)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [19]:
# 3-d example
e=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(e)
e.shape

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


(2, 2, 2)

In [20]:
# get specific element from 3-d
e[0,1,1]

np.int64(4)

In [21]:
e[0,1,:]

array([3, 4])

In [22]:
e[:,1,:]

array([[3, 4],
       [7, 8]])

In [23]:
# To change something
e[:,1,:]=[[7,8],[3,4]]
print(e)

[[[1 2]
  [7 8]]

 [[5 6]
  [3 4]]]


In [24]:
#initialize differnet types of arrays
# ALL 0S Matrix
np.zeros(((2,3,3,2)))

#(2, 3, 3, 2)
 #↑  ↑  ↑  ↑
 #|  |  |  └─ columns
 #|  |  └──── rows
 #|  └─────── number of 3x2 matrices (each block has 3 matrices)
 #└────────── number of groups of those matrices (2 blocks)

 # basically its a 4-D matrix

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [25]:
# All 1s Matrix
np.ones((4,2,2),dtype='int16')
        #↑  ↑  ↑
 #.      |  |  └─ columns
 #.      |  └──── rows
 #       └─────── number of matricess

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int16)

In [26]:
# Any Other Number
np.full((2,2,2,2),99,dtype='float16')

array([[[[99., 99.],
         [99., 99.]],

        [[99., 99.],
         [99., 99.]]],


       [[[99., 99.],
         [99., 99.]],

        [[99., 99.],
         [99., 99.]]]], dtype=float16)

In [27]:
# Any Other NUmber (full-like method)
np.full_like(a,4)

array([4, 4, 4], dtype=int16)

In [28]:
# Random Deciaml Numbers
np.random.rand(2,3,4,4)

array([[[[0.78391805, 0.30292096, 0.02249888, 0.652028  ],
         [0.02322465, 0.22765355, 0.54182265, 0.42001199],
         [0.93236316, 0.75197714, 0.82678176, 0.75606206],
         [0.78634446, 0.86823947, 0.15688889, 0.33855476]],

        [[0.43935991, 0.32399442, 0.70224579, 0.41711396],
         [0.53691915, 0.14027976, 0.77416738, 0.85583066],
         [0.73613919, 0.60477497, 0.44877048, 0.11531295],
         [0.26691463, 0.48828344, 0.26803549, 0.66802878]],

        [[0.14581042, 0.07241305, 0.89183635, 0.65824869],
         [0.45289195, 0.2820004 , 0.08869281, 0.46681365],
         [0.83893302, 0.86768086, 0.7634776 , 0.25285644],
         [0.76311007, 0.0406499 , 0.77341487, 0.21645151]]],


       [[[0.09989212, 0.65929298, 0.9523406 , 0.36419408],
         [0.39880161, 0.82139729, 0.90205795, 0.9168251 ],
         [0.95388488, 0.97531636, 0.01447341, 0.33336972],
         [0.36368797, 0.7409246 , 0.1210304 , 0.15329937]],

        [[0.16453971, 0.50065256, 0.87380572, 

In [29]:
np.random.sample(a.shape)

array([0.57633069, 0.10319631, 0.13250659])

In [30]:
# Random Integer values
# 7 here is a parameter like numbers will be generated from starting number 0 to 7 (7 is excluded though and 0 included means 0-6)
g=np.random.randint(7,size=(2,3,3,3),dtype='int16')
g

array([[[[5, 2, 3],
         [0, 4, 3],
         [0, 3, 6]],

        [[3, 0, 2],
         [3, 3, 0],
         [1, 4, 2]],

        [[0, 5, 2],
         [3, 3, 2],
         [0, 0, 3]]],


       [[[3, 1, 1],
         [0, 6, 0],
         [2, 1, 6]],

        [[2, 4, 0],
         [0, 2, 0],
         [3, 6, 4]],

        [[0, 6, 4],
         [0, 0, 1],
         [4, 6, 1]]]], dtype=int16)

In [31]:
l=np.random.randint(7,size=(2,3,3,3),dtype='int16')
l

array([[[[4, 2, 2],
         [0, 3, 0],
         [2, 6, 2]],

        [[6, 2, 2],
         [0, 0, 4],
         [4, 4, 4]],

        [[1, 0, 5],
         [2, 6, 2],
         [4, 2, 6]]],


       [[[0, 5, 4],
         [0, 5, 0],
         [0, 1, 4]],

        [[5, 2, 5],
         [6, 6, 5],
         [2, 2, 4]],

        [[3, 3, 4],
         [1, 1, 1],
         [3, 4, 4]]]], dtype=int16)

In [32]:
result=g*l
result

array([[[[20,  4,  6],
         [ 0, 12,  0],
         [ 0, 18, 12]],

        [[18,  0,  4],
         [ 0,  0,  0],
         [ 4, 16,  8]],

        [[ 0,  0, 10],
         [ 6, 18,  4],
         [ 0,  0, 18]]],


       [[[ 0,  5,  4],
         [ 0, 30,  0],
         [ 0,  1, 24]],

        [[10,  8,  0],
         [ 0, 12,  0],
         [ 6, 12, 16]],

        [[ 0, 18, 16],
         [ 0,  0,  1],
         [12, 24,  4]]]], dtype=int16)

In [33]:
result.ndim

4

In [34]:
np.random.randint(3,45,size=(2,3,2,2)) # here numbers will be genearted between 3 to 45 (45 is excluded so 3-44)

array([[[[22, 15],
         [33, 23]],

        [[39, 37],
         [22, 17]],

        [[36, 17],
         [39,  8]]],


       [[[ 6, 30],
         [18, 32]],

        [[ 8, 22],
         [ 9, 24]],

        [[ 7, 22],
         [14, 16]]]])

In [35]:
# the idntity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
# repeat an array
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [40]:
# Question 1 
# create a martrix like       1 1 1 1 1
                        #     1 0 0 0 1
                         #    1 0 9 0 1
                          #   1 0 0 0 1
                           #  1 1 1 1 1 

matrix_1=np.ones([5,5])
matrix_1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [39]:
matrix_2= np.zeros([3,3])
matrix_2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [42]:
matrix_2[1,1]=9
matrix_2

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [45]:
matrix_1[1:4,1:4]=matrix_2
matrix_1

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

BE CAREFULL WHEN COPY THE ARRAY

In [ ]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [49]:
b=a.copy()
b[0]=100
b

array([100,   2,   3])