In [2]:
## To import numpy
import numpy as np

In [3]:
## Basics
a=np.array([1,2,3],dtype='int16') #1-D Array    we used (dtype='int16') bcz 1,2,3 are smaller value so to save size and fast processing we used int 16 else we used int64
print(a)
a.ndim

[1 2 3]


1

In [4]:
b=np.array([[1.0,5.0,7.0],[2.0,3.0,9.0]]) #2-D Array
print(b)
b.shape

[[1. 5. 7.]
 [2. 3. 9.]]


(2, 3)

In [5]:
c=np.array([[1,2,3],[4,5,6],[7,8,9]]) #2-D Array
print(c)
c.ndim

[[1 2 3]
 [4 5 6]
 [7 8 9]]


2

In [6]:
#Get Dimensions
a.ndim

1

In [7]:
# Get Shape
a.shape

(3,)

In [8]:
# Get Type
a.dtype

dtype('int16')

In [9]:
# Get Size
a.itemsize

2

In [10]:
# Get Total Size
a.nbytes

6

In [11]:
d=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(d)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [12]:
# lets say from above we want only one specific element lets say '13'
# [row,column]
d[1,5]

np.int64(13)

In [13]:
# You can also do like this 
d[1,-2]

np.int64(13)

In [14]:
# To get a specific row 
d[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [15]:
# To get a specif column
d[:,2]

array([ 3, 10])

In [16]:
# Getting little more fancey [start index: end index: stepsize]
d[0,1:6:2]

array([2, 4, 6])

In [17]:
# change an element in row
d[1,5]=20
print(d)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [18]:
# change elements in col
d[:,2]=[1,2]
print(d)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [19]:
# 3-d example
e=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(e)
e.shape

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


(2, 2, 2)

In [20]:
# get specific element from 3-d
e[0,1,1]

np.int64(4)

In [21]:
e[0,1,:]

array([3, 4])

In [22]:
e[:,1,:]

array([[3, 4],
       [7, 8]])

In [23]:
# To change something
e[:,1,:]=[[7,8],[3,4]]
print(e)

[[[1 2]
  [7 8]]

 [[5 6]
  [3 4]]]


In [24]:
#initialize differnet types of arrays
# ALL 0S Matrix
np.zeros(((2,3,3,2)))

#(2, 3, 3, 2)
 #↑  ↑  ↑  ↑
 #|  |  |  └─ columns
 #|  |  └──── rows
 #|  └─────── number of 3x2 matrices (each block has 3 matrices)
 #└────────── number of groups of those matrices (2 blocks)

 # basically its a 4-D matrix

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [27]:
# All 1s Matrix
np.ones((4,2,2),dtype='int16')
        #↑  ↑  ↑
 #.      |  |  └─ columns
 #.      |  └──── rows
 #       └─────── number of matricess

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int16)

In [34]:
# Any Other Number
np.full((2,2,2,2),99,dtype='float16')

array([[[[99., 99.],
         [99., 99.]],

        [[99., 99.],
         [99., 99.]]],


       [[[99., 99.],
         [99., 99.]],

        [[99., 99.],
         [99., 99.]]]], dtype=float16)

In [36]:
# Any Other NUmber (full-like method)
np.full_like(a,4)

array([4, 4, 4], dtype=int16)

In [40]:
# Random Deciaml Numbers
np.random.rand(2,3,4,4)

array([[[[0.61123711, 0.99100435, 0.96210209, 0.83213665],
         [0.98941691, 0.21736757, 0.56349498, 0.82511461],
         [0.769249  , 0.92375735, 0.4479242 , 0.29585227],
         [0.20925696, 0.64653456, 0.31035172, 0.00371351]],

        [[0.41502851, 0.28353033, 0.43654615, 0.44181553],
         [0.09807063, 0.28441786, 0.51610985, 0.4989273 ],
         [0.61557006, 0.46708183, 0.25071167, 0.08832807],
         [0.08675619, 0.76399207, 0.25928692, 0.8629746 ]],

        [[0.17406078, 0.55041606, 0.13854583, 0.91582901],
         [0.80012212, 0.29064502, 0.10620914, 0.41457521],
         [0.99592806, 0.23134168, 0.92806789, 0.94035524],
         [0.06312838, 0.46602767, 0.66286547, 0.03708677]]],


       [[[0.45901837, 0.3343266 , 0.21612372, 0.85468136],
         [0.14817587, 0.95701974, 0.41558023, 0.09490152],
         [0.11165841, 0.47006052, 0.82638818, 0.37083663],
         [0.69662122, 0.50321456, 0.45711703, 0.44790245]],

        [[0.83620207, 0.94672048, 0.43238396, 

In [41]:
np.random.sample(a.shape)

array([0.8652644 , 0.04606904, 0.9369318 ])

In [ ]:
# Random Integer values
# 7 here is a parameter like numbers will be generated from starting number 0 to 7 (7 is excluded though and 0 included means 0-6)
g=np.random.randint(7,size=(2,3,3,3),dtype='int16')
g

array([[[[1, 4, 1],
         [4, 3, 5],
         [2, 3, 1]],

        [[1, 2, 6],
         [6, 0, 1],
         [0, 2, 6]],

        [[3, 6, 0],
         [2, 2, 0],
         [2, 2, 2]]],


       [[[4, 4, 1],
         [3, 0, 3],
         [4, 4, 0]],

        [[6, 2, 2],
         [1, 1, 2],
         [1, 6, 0]],

        [[5, 5, 5],
         [4, 0, 6],
         [1, 5, 2]]]], dtype=int16)

In [67]:
l=np.random.randint(7,size=(2,3,3,3),dtype='int16')
l

array([[[[1, 0, 4],
         [5, 5, 2],
         [6, 4, 2]],

        [[2, 5, 6],
         [0, 3, 2],
         [3, 6, 3]],

        [[0, 0, 0],
         [2, 1, 4],
         [1, 3, 6]]],


       [[[6, 3, 2],
         [5, 4, 5],
         [0, 4, 6]],

        [[1, 2, 3],
         [3, 4, 2],
         [2, 1, 3]],

        [[3, 4, 6],
         [1, 2, 3],
         [5, 2, 3]]]], dtype=int16)

In [69]:
result=g*l
result

array([[[[ 4,  0, 16],
         [15, 10,  0],
         [36,  8, 10]],

        [[12,  0, 36],
         [ 0,  0,  6],
         [15,  6, 18]],

        [[ 0,  0,  0],
         [ 4,  6, 12],
         [ 5, 15, 12]]],


       [[[30,  6,  0],
         [20, 16,  0],
         [ 0, 24,  6]],

        [[ 2,  0,  0],
         [18,  0,  4],
         [ 8,  3,  0]],

        [[18,  4, 18],
         [ 3,  8,  0],
         [ 5, 12, 15]]]], dtype=int16)

In [73]:
result.ndim

4

In [ ]:
np.random.randint(3,45,size=(2,3,2,2)) # here numbers will be genearted between 3 to 45 (45 is excluded so 3-44)

array([[[[21, 11],
         [39, 42]],

        [[ 6, 12],
         [40, 31]],

        [[23, 19],
         [26, 33]]],


       [[[13,  9],
         [37, 33]],

        [[ 9, 35],
         [32, 44]],

        [[34, 41],
         [19, 40]]]])

In [98]:
# the idntity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# repeat an array
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])