In [91]:
## To import numpy
import numpy as np

In [92]:
## Basics
a=np.array([1,2,3],dtype='int16') #1-D Array    we used (dtype='int16') bcz 1,2,3 are smaller value so to save size and fast processing we used int 16 else we used int64
print(a)
a.ndim

[1 2 3]


1

In [93]:
b=np.array([[1.0,5.0,7.0],[2.0,3.0,9.0]]) #2-D Array
print(b)
b.shape

[[1. 5. 7.]
 [2. 3. 9.]]


(2, 3)

In [94]:
c=np.array([[1,2,3],[4,5,6],[7,8,9]]) #2-D Array
print(c)
c.ndim

[[1 2 3]
 [4 5 6]
 [7 8 9]]


2

In [95]:
#Get Dimensions
a.ndim

1

In [96]:
# Get Shape
a.shape

(3,)

In [97]:
# Get Type
a.dtype

dtype('int16')

In [98]:
# Get Size
a.itemsize

2

In [99]:
# Get Total Size
a.nbytes

6