In [49]:
## To import numpy
import numpy as np

In [50]:
## Basics
a=np.array([1,2,3],dtype='int16') #1-D Array    we used (dtype='int16') bcz 1,2,3 are smaller value so to save size and fast processing we used int 16 else we used int64
print(a)
a.ndim

[1 2 3]


1

In [51]:
b=np.array([[1.0,5.0,7.0],[2.0,3.0,9.0]]) #2-D Array
print(b)
b.shape

[[1. 5. 7.]
 [2. 3. 9.]]


(2, 3)

In [52]:
c=np.array([[1,2,3],[4,5,6],[7,8,9]]) #2-D Array
print(c)
c.ndim

[[1 2 3]
 [4 5 6]
 [7 8 9]]


2

In [53]:
#Get Dimensions
a.ndim

1

In [54]:
# Get Shape
a.shape

(3,)

In [55]:
# Get Type
a.dtype

dtype('int16')

In [56]:
# Get Size
a.itemsize

2

In [57]:
# Get Total Size
a.nbytes

6

In [58]:
d=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(d)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [59]:
# lets say from above we want only one specific element lets say '13'
# [row,column]
d[1,5]

np.int64(13)

In [60]:
# You can also do like this 
d[1,-2]

np.int64(13)

In [62]:
# To get a specific row 
d[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [63]:
# To get a specif column
d[:,2]

array([ 3, 10])

In [76]:
# Getting little more fancey [start index: end index: stepsize]
d[0,1:6:2]

array([2, 4, 6])

In [ ]:
# change an element in row
d[1,5]=20
print(d)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [78]:
# change elements in col
d[:,2]=[1,2]
print(d)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [80]:
# 3-d example
e=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(e)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [81]:
# get specific element from 3-d
e[0,1,1]

np.int64(4)

In [82]:
e[0,1,:]

array([3, 4])

In [83]:
e[:,1,:]

array([[3, 4],
       [7, 8]])

In [84]:
# To change something
e[:,1,:]=[[7,8],[3,4]]
print(e)

[[[1 2]
  [7 8]]

 [[5 6]
  [3 4]]]
