In [3]:
## To import numpy
import numpy as np

In [4]:
## Basics
a=np.array([1,2,3],dtype='int16') #1-D Array    we used (dtype='int16') bcz 1,2,3 are smaller value so to save size and fast processing we used int 16 else we used int64
print(a)
a.ndim

[1 2 3]


1

In [5]:
b=np.array([[1.0,5.0,7.0],[2.0,3.0,9.0]]) #2-D Array
print(b)
b.shape

[[1. 5. 7.]
 [2. 3. 9.]]


(2, 3)

In [6]:
c=np.array([[1,2,3],[4,5,6],[7,8,9]]) #2-D Array
print(c)
c.ndim

[[1 2 3]
 [4 5 6]
 [7 8 9]]


2

In [7]:
#Get Dimensions
a.ndim

1

In [8]:
# Get Shape
a.shape

(3,)

In [9]:
# Get Type
a.dtype

dtype('int16')

In [10]:
# Get Size
a.itemsize

2

In [11]:
# Get Total Size
a.nbytes

6

In [12]:
d=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(d)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [13]:
# lets say from above we want only one specific element lets say '13'
# [row,column]
d[1,5]

np.int64(13)

In [14]:
# You can also do like this 
d[1,-2]

np.int64(13)

In [15]:
# To get a specific row 
d[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [16]:
# To get a specif column
d[:,2]

array([ 3, 10])

In [17]:
# Getting little more fancey [start index: end index: stepsize]
d[0,1:6:2]

array([2, 4, 6])

In [18]:
# change an element in row
d[1,5]=20
print(d)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [19]:
# change elements in col
d[:,2]=[1,2]
print(d)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [20]:
# 3-d example
e=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(e)
e.shape

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


(2, 2, 2)

In [21]:
# get specific element from 3-d
e[0,1,1]

np.int64(4)

In [22]:
e[0,1,:]

array([3, 4])

In [23]:
e[:,1,:]

array([[3, 4],
       [7, 8]])

In [24]:
# To change something
e[:,1,:]=[[7,8],[3,4]]
print(e)

[[[1 2]
  [7 8]]

 [[5 6]
  [3 4]]]


In [25]:
#initialize differnet types of arrays
# ALL 0S Matrix
np.zeros(((2,3,3,2)))

#(2, 3, 3, 2)
 #↑  ↑  ↑  ↑
 #|  |  |  └─ columns
 #|  |  └──── rows
 #|  └─────── number of 3x2 matrices (each block has 3 matrices)
 #└────────── number of groups of those matrices (2 blocks)

 # basically its a 4-D matrix

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [26]:
# All 1s Matrix
np.ones((4,2,2),dtype='int16')
        #↑  ↑  ↑
 #.      |  |  └─ columns
 #.      |  └──── rows
 #       └─────── number of matricess

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int16)

In [27]:
# Any Other Number
np.full((2,2,2,2),99,dtype='float16')

array([[[[99., 99.],
         [99., 99.]],

        [[99., 99.],
         [99., 99.]]],


       [[[99., 99.],
         [99., 99.]],

        [[99., 99.],
         [99., 99.]]]], dtype=float16)

In [28]:
# Any Other NUmber (full-like method)
np.full_like(a,4)

array([4, 4, 4], dtype=int16)

In [29]:
# Random Deciaml Numbers
np.random.rand(2,3,4,4)

array([[[[0.40268875, 0.30603568, 0.29430631, 0.21060568],
         [0.81048338, 0.22261962, 0.31952256, 0.9414992 ],
         [0.57045847, 0.37769184, 0.32471339, 0.93390721],
         [0.89862292, 0.68509264, 0.07597226, 0.86306156]],

        [[0.67600363, 0.36212286, 0.714671  , 0.16339283],
         [0.49206639, 0.66895337, 0.49276169, 0.44485062],
         [0.76781089, 0.92291682, 0.51059217, 0.80063816],
         [0.09461031, 0.73269993, 0.12600743, 0.71913876]],

        [[0.64165333, 0.8003718 , 0.24245169, 0.12953846],
         [0.87243045, 0.2925697 , 0.83794126, 0.4941627 ],
         [0.60529817, 0.64765664, 0.07031456, 0.49962755],
         [0.0048724 , 0.91427936, 0.62479991, 0.40929432]]],


       [[[0.50481409, 0.30598729, 0.07508528, 0.80461891],
         [0.4897992 , 0.86752317, 0.20784982, 0.9149034 ],
         [0.9318744 , 0.91148455, 0.8069399 , 0.57152208],
         [0.66162289, 0.37267526, 0.47209842, 0.69590488]],

        [[0.45000382, 0.44088983, 0.15909605, 

In [30]:
np.random.sample(a.shape)

array([0.33834568, 0.83786679, 0.06706669])

In [31]:
# Random Integer values
# 7 here is a parameter like numbers will be generated from starting number 0 to 7 (7 is excluded though and 0 included means 0-6)
g=np.random.randint(7,size=(2,3,3,3),dtype='int16')
g

array([[[[2, 1, 5],
         [4, 5, 1],
         [3, 4, 0]],

        [[6, 3, 4],
         [0, 1, 6],
         [6, 4, 5]],

        [[3, 0, 3],
         [2, 3, 6],
         [6, 0, 0]]],


       [[[0, 4, 4],
         [3, 1, 2],
         [0, 3, 6]],

        [[6, 3, 6],
         [5, 1, 3],
         [5, 1, 4]],

        [[6, 5, 6],
         [2, 5, 5],
         [0, 0, 5]]]], dtype=int16)

In [32]:
l=np.random.randint(7,size=(2,3,3,3),dtype='int16')
l

array([[[[3, 4, 0],
         [5, 5, 6],
         [5, 2, 0]],

        [[1, 0, 3],
         [1, 1, 3],
         [0, 5, 2]],

        [[4, 3, 0],
         [1, 0, 4],
         [4, 5, 6]]],


       [[[0, 1, 5],
         [2, 3, 0],
         [1, 5, 5]],

        [[1, 3, 1],
         [0, 5, 3],
         [5, 1, 2]],

        [[5, 1, 2],
         [3, 6, 4],
         [5, 0, 1]]]], dtype=int16)

In [33]:
result=g*l
result

array([[[[ 6,  4,  0],
         [20, 25,  6],
         [15,  8,  0]],

        [[ 6,  0, 12],
         [ 0,  1, 18],
         [ 0, 20, 10]],

        [[12,  0,  0],
         [ 2,  0, 24],
         [24,  0,  0]]],


       [[[ 0,  4, 20],
         [ 6,  3,  0],
         [ 0, 15, 30]],

        [[ 6,  9,  6],
         [ 0,  5,  9],
         [25,  1,  8]],

        [[30,  5, 12],
         [ 6, 30, 20],
         [ 0,  0,  5]]]], dtype=int16)

In [34]:
result.ndim

4

In [35]:
np.random.randint(3,45,size=(2,3,2,2)) # here numbers will be genearted between 3 to 45 (45 is excluded so 3-44)

array([[[[32,  8],
         [42, 15]],

        [[ 8, 11],
         [15, 29]],

        [[25, 30],
         [21,  8]]],


       [[[26, 23],
         [18, 24]],

        [[34, 26],
         [37, 31]],

        [[19, 30],
         [27, 27]]]])

In [36]:
# the idntity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
# repeat an array
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [38]:
# Question 1 
# create a martrix like       1 1 1 1 1
                        #     1 0 0 0 1
                         #    1 0 9 0 1
                          #   1 0 0 0 1
                           #  1 1 1 1 1 

matrix_1=np.ones([5,5])
matrix_1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [39]:
matrix_2= np.zeros([3,3])
matrix_2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [40]:
matrix_2[1,1]=9
matrix_2

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [41]:
matrix_1[1:4,1:4]=matrix_2
matrix_1

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

BE CAREFULL WHEN COPY THE ARRAY

In [42]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [43]:
b=a.copy()
b[0]=100
b

array([100,   2,   3])

MATHEMATICS

In [44]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [47]:
a+2

array([3, 4, 5, 6])

In [50]:
a-2

array([-1,  0,  1,  2])

In [51]:
a*2

array([2, 4, 6, 8])

In [52]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [53]:
a**2

array([ 1,  4,  9, 16])

In [55]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

LINEAR ALGEBRA

In [ ]:
c=np.ones((2,3))
print(c)

d=np.full((3,2),5)
print(d)

[[1. 1. 1.]
 [1. 1. 1.]]
[[5 5]
 [5 5]
 [5 5]]


In [61]:
np.matmul(a,b)

array([[15., 15.],
       [15., 15.]])

In [ ]:
## To find Determinent of Matrix
g=np.identity(3)
print(g)
np.linalg.det(g)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


np.float64(1.0)

In [65]:
np.linalg.trace(g)

np.float64(3.0)

STATISTICS

In [ ]:
stats=np.array([[1,2,3],[4,5,6]])
print(stats)

[[1 2 3]
 [4 5 6]]


In [70]:
np.min(stats)

np.int64(1)

In [72]:
np.max(stats,axis=0)

array([4, 5, 6])

In [73]:
np.max(stats,axis=1)

array([3, 6])

In [74]:
np.sum(stats)

np.int64(21)

Reorganizing Arrays

In [77]:
before=np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after=before.reshape(4,2)
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


Vertically Stacking Matrices

In [79]:
v1=np.array([1,2,3,4,5,6])
v2=np.array([6,7,3,9,1,5])
v_stack=np.vstack([v1,v2,v2,v2,v1])
print(v_stack)

[[1 2 3 4 5 6]
 [6 7 3 9 1 5]
 [6 7 3 9 1 5]
 [6 7 3 9 1 5]
 [1 2 3 4 5 6]]


In [84]:
## Horizontal Stacking Martices

v3=np.ones([2,2])
v4=np.zeros([2,4])
h_stack=np.hstack([v4,v4,v3,v4,v3])
print(h_stack)

[[0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 1. 1.]]


MISCELLANEOUS THINGS

LOAD DATA FROM FILE

In [94]:
filedata=np.genfromtxt('data.txt', delimiter=',')
finaldata=filedata.astype('int32')
print(finaldata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


BOOLEAN MASKING AND ADVANCED INDEXING

In [95]:
filedata>50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [96]:
filedata[filedata>50]

array([196.,  75., 766.,  75.,  55., 999.,  78.,  76.,  88.])

In [97]:
np.any(filedata>50, axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [98]:
np.all(filedata>50 , axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [99]:
((filedata>50)&(filedata<100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])